name: Schedule Run Code and Send Email

on:
  schedule:
    - cron: '25 17 * * *' # This will run the workflow every day at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry install

    - name: Run script
      run: |
        poetry run python check_dmarc.py > output.txt

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: GitHub Action result
        body: file://output.txt
        to: ${{ secrets.MAIL_TO }}
        from: ${{ secrets.MAIL_FROM }}
